// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable representation of an agent profile.
 */
export type AgentProfileDto = {
/**
 * Identity of the agent profile.
 */
id: string,
/**
 * Display name.
 */
display_name: string,
/**
 * Preferred harness: `"acp"`, `"terminal"`, or `"native"`.
 */
preferred_harness: string,
/**
 * Memory mode: `"off"`, `"session"`, or `"long_term"`.
 */
memory_mode: string,
/**
 * Creation timestamp.
 */
created_at: number,
/**
 * Last update timestamp.
 */
updated_at: number, };
