// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A JSON payload bounded by an explicit, runtime-provided limit.
 *
 * The payload is stored as a [`serde_json::Value`]; map keys stay sorted
 * because the `preserve_order` feature is not enabled, which keeps
 * serialization deterministic.
 */
export type BoundedPayload = unknown;
