// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for cancelling an in-flight turn (`cancel_turn`).
 */
export type CancelTurnCommand = {
/**
 * Target thread.
 */
thread_id: string,
/**
 * Specific turn to cancel, if scoped.
 */
turn_id: string | null,
/**
 * Specific operation ID to cancel, if known.
 */
target_operation_id: string | null, };
