// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A canonical capability identifier, e.g. `event.streaming`.
 */
export type CapabilityId = string;
