// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A deterministic set of declared capabilities keyed by canonical id.
 *
 * The map is ordered, so serialization and iteration are deterministic.
 */
export type CapabilitySet = { [key in string]: "supported" | "unsupported" };
