// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One endpoint's declared support state for a capability.
 */
export type CapabilitySupport = "supported" | "unsupported";
