// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandKind } from "./CommandKind";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * A versioned command envelope. No transport is attached; encoding is a
 * plain JSON contract so any local IPC transport can carry it.
 */
export type CommandEnvelope = {
/**
 * The protocol version negotiated for this connection.
 */
protocol_version: ProtocolVersion,
/**
 * The Altior operation this command belongs to (for idempotency).
 */
operation_id: string,
/**
 * The command discriminator.
 */
kind: CommandKind,
/**
 * Optional bounded JSON payload.
 */
payload: unknown,
/**
 * When the sender issued the command. Supplied by the sender's clock;
 * fixtures use constants.
 */
issued_at: number, };
