// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The command kinds defined by protocol version 1.
 */
export type CommandKind = "ping" | "request_snapshot" | "cancel";
