// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for confirming a candidate memory record (`confirm_memory`).
 */
export type ConfirmMemoryCommand = {
/**
 * ID of the candidate memory to confirm.
 */
memory_id: string, };
