// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating or updating an agent profile (`configure_agent`).
 */
export type ConfigureAgentCommand = {
/**
 * Profile ID to update, or `None` to create a new profile.
 */
agent_profile_id: string | null,
/**
 * Display name (1..=256 bytes).
 */
display_name: string,
/**
 * Preferred harness: `"acp"`, `"terminal"`, or `"native"`.
 */
preferred_harness: string,
/**
 * Memory mode: `"off"`, `"session"`, or `"long_term"`.
 */
memory_mode: string, };
