// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One identity document selected into a wire prompt.
 */
export type ContextIdentityEntryDto = {
/**
 * The identity document id.
 */
document_id: string,
/**
 * The document kind.
 */
kind: string,
/**
 * Estimated tokens of the rendered entry.
 */
tokens: number, };
