// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recorded degradation when assembly proceeded with reduced information.
 */
export type ContextDegradationDto = {
/**
 * Canonical machine-readable code (e.g. `memory_query_truncated`).
 */
code: string,
/**
 * Bounded human-readable explanation.
 */
detail: string, };
