// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One retrieved memory that was dropped from a wire prompt.
 */
export type ContextDroppedEntryDto = {
/**
 * The memory record id.
 */
memory_id: string,
/**
 * Estimated tokens the entry would have consumed.
 */
tokens: number,
/**
 * Rank of the entry at drop time (1 = highest score).
 */
rank: number,
/**
 * Why the entry was dropped (`"budget_exhausted"`).
 */
reason: string, };
