// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextDegradationDto } from "./ContextDegradationDto";
import type { ContextDroppedEntryDto } from "./ContextDroppedEntryDto";
import type { ContextIdentityEntryDto } from "./ContextIdentityEntryDto";
import type { ContextMemoryEntryDto } from "./ContextMemoryEntryDto";
import type { ContextTokenBudgetDto } from "./ContextTokenBudgetDto";

/**
 * The deterministic audit record of one turn's context assembly (ADR 0018).
 */
export type ContextSnapshotDto = {
/**
 * The turn this snapshot assembled context for.
 */
turn_id: string,
/**
 * The thread the turn belongs to.
 */
thread_id: string,
/**
 * Agent memory mode at assembly time (`"off"` | `"session"` | `"long_term"`).
 */
memory_mode: string,
/**
 * When the snapshot was assembled.
 */
created_at: number,
/**
 * Whether the wire prompt was byte-identical to the user prompt.
 */
passthrough: boolean,
/**
 * Token accounting.
 */
budget: ContextTokenBudgetDto,
/**
 * Identity documents injected, in render order.
 */
identity: Array<ContextIdentityEntryDto>,
/**
 * Memories injected, in rank order.
 */
memories: Array<ContextMemoryEntryDto>,
/**
 * Memories retrieved but dropped, in rank order.
 */
dropped: Array<ContextDroppedEntryDto>,
/**
 * Recorded degradation, if any.
 */
degraded: ContextDegradationDto | null,
/**
 * Optional rendered wire prompt (bounded), when retained.
 */
rendered_prompt: string | null, };
