// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One confirmed memory selected into a wire prompt, with explainability.
 */
export type ContextMemoryEntryDto = {
/**
 * The memory record id.
 */
memory_id: string,
/**
 * Memory kind.
 */
kind: string,
/**
 * Memory scope kind (`"global"` | `"project"` | `"thread"`).
 */
scope_kind: string,
/**
 * Optional scope target.
 */
scope_target: string | null,
/**
 * Confidence percentage (0..=100).
 */
confidence: number,
/**
 * Whether the memory source was explicit.
 */
explicit: boolean,
/**
 * Estimated tokens of the rendered entry.
 */
tokens: number,
/**
 * Composite retrieval score.
 */
score: number,
/**
 * Human-readable selection rationale from the ranking engine.
 */
why_selected: string,
/**
 * Provenance thread id, when known.
 */
provenance_thread_id: string | null,
/**
 * Provenance turn id, when known.
 */
provenance_turn_id: string | null, };
