// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token accounting for one assembled turn context.
 */
export type ContextTokenBudgetDto = {
/**
 * Maximum identity tokens the policy allows.
 */
identity_limit_tokens: number,
/**
 * Maximum memory tokens the policy allows.
 */
memory_limit_tokens: number,
/**
 * Estimated tokens of the user's original prompt.
 */
prompt_tokens: number,
/**
 * Tokens consumed by the injected identity block (including framing).
 */
identity_tokens: number,
/**
 * Tokens consumed by the injected memory block (including framing).
 */
memory_tokens: number,
/**
 * Total tokens of the assembled wire prompt.
 */
total_tokens: number, };
