// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductVersion } from "./ProductVersion";
import type { ProtocolVersion } from "./ProtocolVersion";
import type { RetainedWindow } from "./RetainedWindow";

/**
 * Core's first message after a successful handshake (ADR 0006).
 */
export type CoreGreeting = {
/**
 * The protocol version negotiated for this connection.
 */
protocol_version: ProtocolVersion,
/**
 * Identity of this Core launch. Differs across restarts.
 */
instance_id: string,
/**
 * Core's product build version, for diagnostics only.
 */
core_version: ProductVersion,
/**
 * The retained event window, or `None` on a fresh Core with no events.
 */
retained: RetainedWindow | null, };
