// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySet } from "./CapabilitySet";
import type { ProductVersion } from "./ProductVersion";
import type { ProtocolVersionRange } from "./ProtocolVersionRange";

/**
 * Core's handshake reply.
 */
export type CoreHello = { 
/**
 * Protocol versions this Core build can speak, inclusive.
 */
supported_versions: ProtocolVersionRange, 
/**
 * Core's product build version, for diagnostics only.
 */
core_version: ProductVersion, 
/**
 * Capabilities this Core build explicitly declares.
 */
capabilities: CapabilitySet, };
