// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for correcting an existing confirmed memory (`correct_memory`).
 *
 * This supersedes the original record and creates a new confirmed memory.
 */
export type CorrectMemoryCommand = {
/**
 * ID of the confirmed memory to correct / supersede.
 */
memory_id: string,
/**
 * New corrected content text.
 */
content: string,
/**
 * Optional new scope kind; if omitted, preserves existing scope.
 */
scope_kind?: string | null,
/**
 * Optional new scope target identifier.
 */
scope_target?: string | null,
/**
 * Optional new semantic kind; if omitted, preserves existing kind.
 */
kind?: string | null,
/**
 * Optional new sensitivity level.
 */
sensitivity?: string | null, };
