// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating a thread (`create_thread`).
 */
export type CreateThreadCommand = {
/**
 * Agent profile to associate with this thread.
 */
agent_profile_id: string,
/**
 * Optional thread title (up to 512 bytes).
 */
title: string | null,
/**
 * Optional project association.
 */
project_id: string | null, };
