// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for deleting an identity document (`delete_identity_document`).
 */
export type DeleteIdentityDocumentCommand = {
/**
 * ID of the identity document to delete.
 */
document_id: string, };
