// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySet } from "./CapabilitySet";
import type { ProductVersion } from "./ProductVersion";
import type { ProtocolVersionRange } from "./ProtocolVersionRange";

/**
 * Desktop's opening handshake message.
 */
export type DesktopHello = { 
/**
 * Protocol versions this Desktop build can speak, inclusive.
 */
supported_versions: ProtocolVersionRange, 
/**
 * Desktop's product build version, for diagnostics only.
 */
desktop_version: ProductVersion, 
/**
 * Capabilities this Desktop build explicitly declares.
 */
capabilities: CapabilitySet, 
/**
 * The per-launch capability token proving this connection may drive
 * Core (`docs/SECURITY.md`, ADR 0006). Validation belongs to the IPC
 * session layer, which authenticates before negotiating; `negotiate()`
 * itself stays pure version/capability math.
 */
launch_token: string, };
