// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for querying runtime diagnostics (`diagnostics`).
 */
export type DiagnosticsCommand = {
/**
 * Optional thread filter.
 */
thread_id: string | null,
/**
 * Maximum diagnostic entries to retrieve.
 */
limit: number | null, };
