// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventBody } from "./EventBody";
import type { ProtocolVersion } from "./ProtocolVersion";
import type { Sequence } from "./Sequence";

/**
 * A versioned event envelope. No transport is attached; encoding is a
 * plain JSON contract so any local IPC transport can carry it.
 */
export type EventEnvelope = {
/**
 * The protocol version negotiated for this connection.
 */
protocol_version: ProtocolVersion,
/**
 * Identity of this event.
 */
event_id: string,
/**
 * The operation this event belongs to, when scoped to one.
 */
operation_id: string | null,
/**
 * The thread this event belongs to, when scoped to one.
 */
thread_id: string | null,
/**
 * The turn this event belongs to, when scoped to one.
 */
turn_id: string | null,
/**
 * The 1-based position of this event within its ordered stream.
 */
sequence: Sequence,
/**
 * When the event occurred. Supplied by the emitting side; fixtures
 * use constants.
 */
occurred_at: number,
/**
 * The event discriminator and payload.
 */
body: EventBody, };
