// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of an event envelope: a known normalized event or a safely
 * preserved unknown future event.
 */
export type EventBody = { kind: "turn.started" } | { kind: "message.delta"; text: string } | { kind: "turn.completed" } | { kind: string; diagnostic: string };
