// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for tombstoning / forgetting a confirmed memory (`forget_memory`).
 */
export type ForgetMemoryCommand = {
/**
 * ID of the memory to forget.
 */
memory_id: string, };
