// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for retrieving context snapshot explainability record(s) (`get_context_snapshot`).
 */
export type GetContextSnapshotCommand = {
/**
 * Target turn ID for retrieving a single context snapshot.
 */
turn_id?: string | null,
/**
 * Target thread ID for listing context snapshots of a thread.
 */
thread_id?: string | null,
/**
 * Maximum items to return when querying by thread (1..=50).
 */
limit?: number | null, };
