// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnCursorDto } from "./TurnCursorDto";

/**
 * Payload for paginating turn history (`get_history`).
 */
export type GetHistoryCommand = {
/**
 * Owning thread identity.
 */
thread_id: string,
/**
 * Cursor for turn pagination.
 */
cursor: TurnCursorDto | null,
/**
 * Maximum turns to return (bounded to 500).
 */
limit: number | null, };
