// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable representation of a harness launch binding.
 *
 * NOTE: In accordance with ADR 0006 / ADR 0014, plaintext secrets are NEVER
 * stored or transferred. `secret_refs` holds only opaque reference keys.
 */
export type HarnessBindingDto = {
/**
 * Identity of this harness binding.
 */
id: string,
/**
 * Associated agent profile.
 */
agent_profile_id: string,
/**
 * Executable program path.
 */
program: string,
/**
 * Command-line arguments.
 */
args: Array<string>,
/**
 * Environment variable keys.
 */
env_keys: Array<string>,
/**
 * Opaque secret references (NEVER plaintext values).
 */
secret_refs: Array<string>,
/**
 * Human-readable label.
 */
label: string,
/**
 * Creation timestamp.
 */
created_at: number, };
