// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable configuration for creating or updating a harness launch binding.
 *
 * NOTE: In accordance with ADR 0006 / ADR 0014, plaintext secrets are NEVER
 * stored or transferred. `secret_refs` holds only opaque reference keys.
 */
export type HarnessBindingConfigDto = {
/**
 * Identity of this harness binding, if updating an existing binding.
 */
harness_binding_id?: string | null,
/**
 * Associated agent profile, if scoped.
 */
agent_profile_id?: string | null,
/**
 * Executable program path (bounded).
 */
program: string,
/**
 * Command-line arguments.
 */
args: Array<string>,
/**
 * Environment variable keys to pass.
 */
env_keys: Array<string>,
/**
 * Opaque secret references (NEVER plaintext values).
 */
secret_refs: Array<string>,
/**
 * Human-readable label.
 */
label?: string | null, };
