// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bounded timeline record projected from the domain journal
 * (ADR 0020). Live events and history pages reduce through the same
 * client logic, so this vocabulary mirrors the live event kinds.
 */
export type HistoryEntryDto = { "entry_kind": "user_message",
/**
 * Journal event identity.
 */
event_id: string,
/**
 * Owning turn.
 */
turn_id: string,
/**
 * Journal position (total order within the thread).
 */
seq: number,
/**
 * Prompt text (bounded at write time).
 */
text: string,
/**
 * When the fact was journaled.
 */
occurred_at: number, } | { "entry_kind": "assistant_delta", event_id: string, turn_id: string, seq: number, text: string, occurred_at: number, } | { "entry_kind": "permission", event_id: string, turn_id: string, seq: number,
/**
 * Permission kind: `"execute"`, `"read"`, `"write"`, `"network"`.
 */
permission_kind: string,
/**
 * Bounded description of the requested action.
 */
description: string,
/**
 * Decision at journal time: `"pending"`, `"approved"`, `"denied"`.
 */
decision: string, occurred_at: number, } | { "entry_kind": "permission_decision", event_id: string,
/**
 * Identity of the originally requested permission event.
 */
permission_event_id: string, turn_id: string, seq: number, decision: string, occurred_at: number, } | { "entry_kind": "turn_state", event_id: string, turn_id: string, seq: number,
/**
 * `"completed"`, `"cancelled"`, or `"failed"`.
 */
state: string,
/**
 * Failure/cancel reason, when present.
 */
reason: string | null,
/**
 * Delivery classification for failed turns, when present.
 */
delivery: string | null, occurred_at: number, } | { "entry_kind": "unknown", event_id: string, seq: number,
/**
 * Preserved journal kind string (bounded).
 */
kind: string,
/**
 * Bounded diagnostic describing the unprojectable row.
 */
diagnostic: string, };
