// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Journal-seq cursor for paginating timeline entries toward the past.
 */
export type HistoryCursorDto = {
/**
 * Journal seq of the oldest entry already fetched.
 */
seq: number, };
