// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable representation of a device-local identity document.
 */
export type IdentityDocumentDto = {
/**
 * Identity document id (`idd_...`).
 */
document_id: string,
/**
 * Semantic classification (`"name"`, `"about"`, `"preference"`, `"instruction"`).
 */
kind: string,
/**
 * Bounded document content.
 */
content: string,
/**
 * Creation timestamp.
 */
created_at: number,
/**
 * Last update timestamp.
 */
updated_at: number, };
