// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The known normalized event kinds defined by protocol version 1.
 *
 * This is the smallest sample of the documented normalized stream needed
 * by envelope fixtures; the full taxonomy lands with the P1 domain
 * runtime.
 */
export type KnownEvent = { "kind": "turn.started" } | { "kind": "message.delta", 
/**
 * The bounded delta text.
 */
text: string, } | { "kind": "turn.completed" };
