// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque per-launch capability token (ADR 0006).
 */
export type LaunchToken = string;
