// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryCursorDto } from "./MemoryCursorDto";

/**
 * Payload for listing memories with optional filtering and bounded pagination (`list_memories`).
 */
export type ListMemoriesCommand = {
/**
 * Scope kind filter: `"global"`, `"person"`, `"project"`, or `"thread"`.
 */
scope_kind?: string | null,
/**
 * Scope target identifier (e.g. `project_id` or `thread_id`).
 */
scope_target?: string | null,
/**
 * State filter: `"candidate"`, `"confirmed"`, `"rejected"`, `"superseded"`, `"forgotten"`, `"expired"`.
 */
state?: string | null,
/**
 * Maximum items to return (1..=100).
 */
limit?: number | null,
/**
 * Pagination cursor from a prior page response.
 */
cursor?: MemoryCursorDto | null, };
