// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadCursorDto } from "./ThreadCursorDto";

/**
 * Payload for listing threads with bounded pagination (`list_threads`).
 */
export type ListThreadsCommand = {
/**
 * Starting cursor for pagination.
 */
cursor: ThreadCursorDto | null,
/**
 * Maximum items to return (bounded to 200).
 */
limit: number | null, };
