// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for listing identity documents (`list_identity_documents`).
 */
export type ListIdentityDocumentsCommand = {
/**
 * Maximum items to return (1..=32).
 */
limit?: number | null, };
