// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor for memory pagination.
 */
export type MemoryCursorDto = {
/**
 * Timestamp of the last row.
 */
updated_at: number,
/**
 * Memory identifier tie-breaker of the last row.
 */
memory_id: string, };
