// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryCursorDto } from "./MemoryCursorDto";
import type { MemoryRecordDto } from "./MemoryRecordDto";

/**
 * Paginated memory list response.
 */
export type MemoryListResponseDto = {
/**
 * Memories returned in this page.
 */
memories: Array<MemoryRecordDto>,
/**
 * Cursor for the next page, or None if no more records.
 */
next_cursor: MemoryCursorDto | null,
/**
 * Whether more memories exist beyond this page.
 */
has_more: boolean, };
