// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for a persistent memory record (ADR 0017 / ADR 0018).
 */
export type MemoryRecordDto = {
/**
 * Unique identity of this memory record (`mem_...`).
 */
memory_id: string,
/**
 * Bounded memory content.
 */
content: string,
/**
 * Scope kind (`"global"`, `"person"`, `"project"`, `"thread"`).
 */
scope_kind: string,
/**
 * Scope target identifier if scoped to person, project, or thread.
 */
scope_target: string | null,
/**
 * Semantic kind (`"fact"`, `"preference"`, `"instruction"`, `"summary"`).
 */
kind: string,
/**
 * Current lifecycle state (`"candidate"`, `"confirmed"`, `"rejected"`, `"superseded"`, `"forgotten"`, `"expired"`).
 */
state: string,
/**
 * Confidence percentage (0..=100).
 */
confidence: number,
/**
 * Sensitivity level (`"normal"`, `"sensitive"`).
 */
sensitivity: string,
/**
 * Provenance source (`"explicit"`, `"inferred"`).
 */
source: string,
/**
 * Whether this record was explicitly created by the user.
 */
explicit: boolean,
/**
 * Thread provenance ID, if associated with a conversation.
 */
provenance_thread_id: string | null,
/**
 * Turn provenance ID, if associated with a conversation turn.
 */
provenance_turn_id: string | null,
/**
 * Optional excerpt from which this memory was derived.
 */
excerpt: string | null,
/**
 * Creation timestamp.
 */
created_at: number,
/**
 * Last update timestamp.
 */
updated_at: number,
/**
 * Optional expiration timestamp.
 */
expires_at: bigint | null,
/**
 * Successor memory ID that superseded this record, if any.
 */
superseded_by: string | null, };
