// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySet } from "./CapabilitySet";
import type { ProductVersion } from "./ProductVersion";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * The result of a successful handshake negotiation.
 */
export type NegotiatedHandshake = {
/**
 * The highest protocol version common to both sides.
 */
selected_version: ProtocolVersion,
/**
 * Desktop's product build version, carried for diagnostics.
 */
desktop_version: ProductVersion,
/**
 * Core's product build version, carried for diagnostics.
 */
core_version: ProductVersion,
/**
 * Capabilities both sides explicitly declared supported.
 */
negotiated_capabilities: CapabilitySet,
/**
 * Capabilities declared supported by Desktop only, for diagnostics.
 */
desktop_only: Array<string>,
/**
 * Capabilities declared supported by Core only, for diagnostics.
 */
core_only: Array<string>, };
