// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for opening a thread (`open_thread`).
 */
export type OpenThreadCommand = {
/**
 * Thread to open.
 */
thread_id: string,
/**
 * Maximum turn history items to return in initial snapshot (bounded to 500).
 */
history_limit: number | null, };
