// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable representation of a user permission request/decision.
 */
export type PermissionDto = {
/**
 * Identity of the permission request event.
 */
event_id: string,
/**
 * Owning turn identity.
 */
turn_id: string,
/**
 * Owning thread identity.
 */
thread_id: string,
/**
 * Kind of permission: `"execute"`, `"read"`, `"write"`, or `"network"`.
 */
kind: string,
/**
 * Bounded description of the requested action.
 */
description: string,
/**
 * Decision: `"approved"`, `"denied"`, or `"pending"`.
 */
decision: string,
/**
 * When permission was requested.
 */
requested_at: number,
/**
 * When permission was decided, if resolved.
 */
decided_at: bigint | null, };
