// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `major.minor.patch` product build version.
 *
 * Product versions travel through the handshake for diagnostics and
 * upgrade prompts only. They never gate protocol behavior; capability
 * support is negotiated explicitly instead of being inferred from a
 * version string.
 */
export type ProductVersion = { 
/**
 * Major component.
 */
major: number, 
/**
 * Minor component.
 */
minor: number, 
/**
 * Patch component.
 */
patch: number, };
