// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for proposing or creating a memory record (`propose_memory`).
 */
export type ProposeMemoryCommand = {
/**
 * Memory content text.
 */
content: string,
/**
 * Scope kind: `"global"`, `"person"`, `"project"`, or `"thread"`.
 */
scope_kind: string,
/**
 * Scope target identifier if scoped to person, project, or thread.
 */
scope_target?: string | null,
/**
 * Semantic kind: `"fact"`, `"preference"`, `"instruction"`, or `"summary"`.
 */
kind: string,
/**
 * Sensitivity level: `"normal"` or `"sensitive"`. Defaults to normal.
 */
sensitivity?: string | null,
/**
 * Confidence score (0..=100).
 */
confidence?: number | null,
/**
 * Provenance source: `"explicit"` or `"inferred"`.
 */
source?: string | null,
/**
 * Optional thread provenance.
 */
thread_id?: string | null,
/**
 * Optional turn provenance.
 */
turn_id?: string | null,
/**
 * Optional verbatim excerpt provenance.
 */
excerpt?: string | null, };
