// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * An inclusive range of protocol versions advertised by one endpoint.
 */
export type ProtocolVersionRange = { min: ProtocolVersion, max: ProtocolVersion, };
