// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Desktop/Core IPC protocol version. Versions start at 1.
 */
export type ProtocolVersion = number;
