// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating or updating an identity document (`put_identity_document`).
 */
export type PutIdentityDocumentCommand = {
/**
 * Optional document ID; if omitted, Core generates one.
 */
document_id?: string | null,
/**
 * Semantic classification ("name", "about", "preference", "instruction").
 */
kind: string,
/**
 * Document content (up to 4096 bytes).
 */
content: string, };
