// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for rejecting a candidate memory record (`reject_memory`).
 */
export type RejectMemoryCommand = {
/**
 * ID of the candidate memory to reject.
 */
memory_id: string,
/**
 * Optional rejection reason.
 */
reason?: string | null, };
