// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for requesting a gap-recovery snapshot (`request_snapshot`).
 *
 * ADR 0006: after `stream.gap` or a Core restart, Desktop re-derives visible
 * state from this snapshot envelope. An absent `thread_id` (or a missing
 * payload) requests the thread-list snapshot; a present `thread_id` requests
 * the same [`crate::dto::ThreadSnapshotDto`] envelope `open_thread` uses.
 */
export type RequestSnapshotCommand = {
/**
 * Optional thread to snapshot. Absent means the thread-list surface.
 */
thread_id?: string | null,
/**
 * Maximum turns to include in a thread snapshot (bounded to 500).
 */
history_limit?: number | null, };
