// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for submitting a user permission response (`respond_permission`).
 */
export type RespondPermissionCommand = {
/**
 * Identity of the permission request event being answered.
 */
event_id: string,
/**
 * Decision: `"approved"` or `"denied"`.
 */
decision: string, };
