// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sequence } from "./Sequence";

/**
 * The inclusive range of past events Core still holds in memory.
 */
export type RetainedWindow = { 
/**
 * Oldest retained sequence, inclusive.
 */
from: Sequence, 
/**
 * Newest retained sequence, inclusive.
 */
through: Sequence, };
