// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for querying runtime status (`runtime_status`).
 */
export type RuntimeStatusCommand = {
/**
 * Whether to include redacted diagnostics summary text.
 */
include_diagnostics: boolean, };
