// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Diagnostics and status summary for the Core runtime.
 */
export type RuntimeDiagnosticsDto = {
/**
 * Core process instance ID.
 */
instance_id: string,
/**
 * Health status: `"ready"`, `"busy"`, `"degraded"`, or `"shutting_down"`.
 */
status: string,
/**
 * Number of active threads in memory.
 */
active_threads: number,
/**
 * Number of turns currently executing.
 */
active_turns: number,
/**
 * Redacted diagnostics summary text, if available.
 */
summary: string | null, };
