// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for searching threads (`search_threads`).
 */
export type SearchThreadsCommand = {
/**
 * Query string (bounded to 256 bytes).
 */
query: string,
/**
 * Maximum items to return (bounded to 200).
 */
limit: number | null, };
