// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 1-based position of an event within its ordered stream.
 */
export type Sequence = number;
