// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for starting a turn / sending a prompt (`start_turn`).
 */
export type StartTurnCommand = {
/**
 * Target conversation thread.
 */
thread_id: string,
/**
 * Client-specified turn ID, or `None` for Core to generate.
 */
turn_id: string | null,
/**
 * Prompt text (bounded to 64 KiB).
 */
prompt: string, };
