// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for probing/testing a harness binding (`test_harness_binding`).
 *
 * NOTE: Plaintext secrets are strictly prohibited (ADR 0006, ADR 0014).
 * `secret_refs` holds only opaque reference keys.
 */
export type TestHarnessBindingCommand = {
/**
 * Existing harness binding ID, if probing an already saved binding.
 */
harness_binding_id?: string | null,
/**
 * Program executable path (bounded to 4096 bytes).
 */
program: string,
/**
 * Command arguments.
 */
args: Array<string>,
/**
 * Environment variable keys to pass.
 */
env_keys: Array<string>,
/**
 * Opaque secret references (NEVER plaintext secrets).
 */
secret_refs: Array<string>,
/**
 * Optional label for the binding.
 */
label?: string | null, };
