// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySet } from "./CapabilitySet";

/**
 * Result payload returned upon testing a harness binding.
 */
export type TestHarnessResponseDto = {
/**
 * Whether the binding is alive and functional.
 */
ok: boolean,
/**
 * Capabilities declared/negotiated with the agent harness.
 */
capabilities: CapabilitySet,
/**
 * Optional diagnostics summary if probe failed or produced notices.
 */
diagnostics?: string | null,
/**
 * Probed harness binding identifier.
 */
probed_binding_id?: string | null, };
