// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryCursorDto } from "./HistoryCursorDto";
import type { HistoryEntryDto } from "./HistoryEntryDto";
import type { TurnCursorDto } from "./TurnCursorDto";
import type { TurnDto } from "./TurnDto";

/**
 * Paginated response for thread turn history.
 *
 * A05 (ADR 0020): `entries` carries the journal-projected timeline
 * records (prompts, assistant deltas, permissions, turn states, bounded
 * unknowns) so the client renders real content after restarts. `turns`
 * remains for turn-level summaries and older clients; both are
 * projections of the same journal.
 */
export type ThreadHistoryResponseDto = {
/**
 * Owning thread identity.
 */
thread_id: string,
/**
 * Turns in this history page.
 */
turns: Array<TurnDto>,
/**
 * Cursor for fetching next history page.
 */
next_cursor: TurnCursorDto | null,
/**
 * Whether additional turns exist.
 */
has_more: boolean,
/**
 * Ordered timeline records (journal projection), oldest first.
 */
entries?: Array<HistoryEntryDto>,
/**
 * Journal-seq cursor for fetching the next (older) entries page.
 */
next_seq_cursor?: HistoryCursorDto | null,
/**
 * The thread's journal high-water seq at query time (live catch-up point).
 */
high_water_seq?: number | null, };
