// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadDto } from "./ThreadDto";
import type { TurnDto } from "./TurnDto";

/**
 * Summary item in a thread list view.
 */
export type ThreadSummaryDto = {
/**
 * The thread record.
 */
thread: ThreadDto,
/**
 * The most recent turn in this thread, if any.
 */
last_turn: TurnDto | null,
/**
 * Currently active turn, if any.
 */
active_turn: TurnDto | null, };
