// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable representation of a conversation thread.
 */
export type ThreadDto = {
/**
 * Identity of the thread.
 */
id: string,
/**
 * Associated agent profile.
 */
agent_profile_id: string,
/**
 * Thread title (bounded string).
 */
title: string,
/**
 * Lifecycle state: `"open"`, `"pinned"`, or `"archived"`.
 */
state: string,
/**
 * Optional associated project reference.
 */
project_id: string | null,
/**
 * Thread creation timestamp.
 */
created_at: number,
/**
 * Thread last updated timestamp.
 */
updated_at: number, };
