// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnCursorDto } from "./TurnCursorDto";
import type { TurnDto } from "./TurnDto";

/**
 * Paginated response for thread turn history.
 */
export type ThreadHistoryResponseDto = {
/**
 * Owning thread identity.
 */
thread_id: string,
/**
 * Turns in this history page.
 */
turns: Array<TurnDto>,
/**
 * Cursor for fetching next history page.
 */
next_cursor: TurnCursorDto | null,
/**
 * Whether additional turns exist.
 */
has_more: boolean, };
