// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor for paginating threads (newest-first).
 */
export type ThreadCursorDto = {
/**
 * Updated timestamp of the last seen thread.
 */
updated_at: number,
/**
 * Thread ID for tie-breaking.
 */
thread_id: string, };
