// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadCursorDto } from "./ThreadCursorDto";
import type { ThreadSummaryDto } from "./ThreadSummaryDto";

/**
 * Paginated response for thread listing and search.
 */
export type ThreadListResponseDto = {
/**
 * Thread summaries in this page.
 */
threads: Array<ThreadSummaryDto>,
/**
 * Cursor for fetching the next page, if more exist.
 */
next_cursor: ThreadCursorDto | null,
/**
 * Whether additional items exist beyond this page.
 */
has_more: boolean, };
