// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProfileDto } from "./AgentProfileDto";
import type { PermissionDto } from "./PermissionDto";
import type { ThreadDto } from "./ThreadDto";
import type { TurnDto } from "./TurnDto";

/**
 * Bounded snapshot of a full thread including recent turns and pending permissions.
 */
export type ThreadSnapshotDto = {
/**
 * The thread record.
 */
thread: ThreadDto,
/**
 * Associated agent profile, if resolved.
 */
agent_profile: AgentProfileDto | null,
/**
 * Recent turns in this thread (bounded).
 */
turns: Array<TurnDto>,
/**
 * Currently pending permission requests.
 */
pending_permissions: Array<PermissionDto>, };
