// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cursor for paginating turns chronologically.
 */
export type TurnCursorDto = {
/**
 * Started timestamp of the last seen turn.
 */
started_at: number,
/**
 * Turn ID for tie-breaking.
 */
turn_id: string, };
