// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable representation of an execution turn inside a thread.
 */
export type TurnDto = {
/**
 * Identity of the turn.
 */
id: string,
/**
 * Owning thread identity.
 */
thread_id: string,
/**
 * Turn state: `"active"`, `"completed"`, `"cancelled"`, or `"failed"`.
 */
state: string,
/**
 * Prompt delivery classification: `"absent"`, `"confirmed"`, `"rejected"`, or `"indeterminate"`.
 */
delivery_state: string,
/**
 * Associated operation identity, when present.
 */
operation_id: string | null,
/**
 * Turn start timestamp.
 */
started_at: number,
/**
 * Turn finish timestamp, if terminal.
 */
ended_at: bigint | null, };
